name: CI
on:
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize, closed ]
  push:
    branches-ignore:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Build on Platform IO Core
        shell: bash
        run: | 
          # Exit immediately if a command exits with a non-zero status.
          set -e

          # Enable the globstar shell option
          shopt -s globstar
          
          # Make sure we are inside the github workspace
          cd $GITHUB_WORKSPACE

          # Source the PlatformIO setup files
          echo 'export PATH=$PATH:~/.platformio/penv/bin' >> /root/.bashrc
          source /root/.bashrc

          pio run
  
  format:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Run clang-format
        shell: bash
        run: | 
          make format