name: CI
on:
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize, closed ]
  push:
    branches-ignore:
      - master

jobs:
  build:
    name: Build
    # runs-on: ubuntu-22.04
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Build on Platform IO Core (CLI)
        shell: bash
        run: | 
          ci/build-platform_io.sh
          pio run
      

  # cpp_linting:
  #   name: C++ Linting
  #   runs-on: ubuntu-22.04
  #   container: robojackets/urc-baseimage:humble
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v2
  #       with:
  #         submodules: recursive

  #     - name: Run Uncrustify
  #       shell: bash
  #       run: |
  #         source /opt/ros/humble/setup.bash
  #         touch external/AMENT_IGNORE
  #         ament_uncrustify -c ament_code_style.cfg

  # python_linting:
  #   name: Python Linting
  #   runs-on: ubuntu-22.04
  #   container: robojackets/urc-baseimage:humble
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v2
  #       with:
  #         submodules: recursive

  #     - name: Run flake8
  #       shell: bash
  #       run: |
  #         source /opt/ros/humble/setup.bash
  #         ament_flake8 --exclude external
  
  # build_linting:
  #   name: Build Linting
  #   runs-on: ubuntu-22.04
  #   container: robojackets/urc-baseimage:humble
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v2
  #       with:
  #         submodules: recursive

  #     - name: Run xmllint
  #       shell: bash
  #       run: |
  #         source /opt/ros/humble/setup.bash
  #         ament_xmllint --exclude external

  #     - name: Run ament_lint_cmake
  #       shell: bash
  #       run: |
  #         source /opt/ros/humble/setup.bash
  #         touch external/AMENT_IGNORE
  #         ament_lint_cmake